package Window;

import java.awt.BorderLayout;
import java.awt.TextArea;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;

import javax.swing.text.JTextComponent;
import javax.imageio.ImageIO;
import javax.swing.*;

import AnalizadorLexico.AnalizadorLexico;
import AnalizadorLexico.ControladorArchivo;
import AnalizadorLexico.TablaSimbolos;
import AnalizadorSintactico.AnalizadorSintactico;
import AnalizadorSintactico.Parser;

//new TextLineNumber(new JTextPane())

/**
 *
 * @author Joaking
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }
    
    private AnalizadorLexico analizadorLexico;
    private AnalizadorSintactico analizadorSintactico;
    private StringBuilder buffer ;
    private ControladorArchivo archivo; // creo que no va a aca pero para probar
    
    public StringBuilder getArchivo() {
		return buffer;
	}
    
    
    //TODO: Verificar que sea un archivo correcto y no una img, etc.
    
	public class Buscador_o implements ActionListener{
		MainWindow v;
		
		public Buscador_o(MainWindow v){
			super();
			this.v = v;
		}
		
		public void actionPerformed(ActionEvent ae){
		  final JFileChooser fc = new JFileChooser();
		  int result = fc.showOpenDialog(new JFrame("Seleccionar archivo"));
		  
		  if ( result == JFileChooser.APPROVE_OPTION) {
			  try {
				BufferedReader bufferedReader = new BufferedReader(new FileReader(fc.getSelectedFile()));
				String readLine;
				StringBuilder stringBuilder = new StringBuilder();				
				buffer = new StringBuilder();
				//TODO: Check que el \n no arruine nada
				while ((readLine = bufferedReader.readLine())!= null) {
					stringBuilder.append(readLine+"\n");
					buffer.append(readLine+"\n");
				}
				buffer.append("$");
				archivo=new ControladorArchivo(buffer);
				v.set_text(stringBuilder);
				
				
				//aca pongo los llamados al analizador, ver desp donda va
				ControladorArchivo archivo = new ControladorArchivo( buffer );
				/*
				AnalizadorLexico analizadorLexico = new AnalizadorLexico( archivo);
				int token = 1;
				while ( token !=0 )
					token =  analizadorLexico.yylex();
					System.out.println(token);
				
				set_text_output(analizadorLexico.mostrarErrores());				
				*/
				
				
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		  }
	  }
	}
	
	public void set_text(StringBuilder stringBuff){
		jTextArea1.setText(stringBuff.toString());
	}
	
	public void set_text_output(String cadena){
		outPut_TextArea.setContentType("text/html");
		outPut_TextArea.setText(cadena);
	}
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
	    
	private void initComponents() {

        jButton_agregar_archivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        outPut_TextArea = new javax.swing.JTextPane();
        textFieldTokenActual = new javax.swing.JTextField();
        tSimbolPane = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        err_sint = new javax.swing.JButton();
        err_lex = new javax.swing.JButton();
        estruct = new javax.swing.JButton();
        warn = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_agregar_archivo.setText("Agregar arcihvo");
        jButton_agregar_archivo.addActionListener(new Buscador_o(this));

        jLabel1.setText("OutPut");
        jLabel2.setText("Tabla de Simbolos");
        jLabel3.setText("Codigo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFont ( jTextArea1.getFont().deriveFont( 14f ));
        jScrollPane.setViewportView(jTextArea1);
        jScrollPane.setRowHeaderView(new TextLineNumber(jTextArea1));
        button_compilar = new javax.swing.JButton();

        err_sint = new javax.swing.JButton();
        err_lex = new javax.swing.JButton();
        estruct = new javax.swing.JButton();
        warn = new javax.swing.JButton();
        
        tSimbolPane.setEditable(false);
        tSimbolPane.getFont().deriveFont( 14f );
		tSimbolPane.setContentType("text/html");
//        outPut_TextArea.setColumns(20);
//        outPut_TextArea.setRows(5);
        outPut_TextArea.setEditable(false);
        
        jScrollPane3.setViewportView(outPut_TextArea);
        jScrollPane3.setFont ( jScrollPane3.getFont().deriveFont( 14f ));

        
        button_compilar.setText("Compilar");
        button_compilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //Ejecutar el metodo para compilar
            	TablaSimbolos ts = new TablaSimbolos();
            	analizadorLexico = new AnalizadorLexico(archivo,ts);
            	analizadorSintactico = new AnalizadorSintactico( );
            	
                Parser parser;
                parser = new Parser();
                parser.setLexico(analizadorLexico);
                parser.setTS(ts);
                parser.setSintactico(analizadorSintactico);
                parser.setControladorArchivo(archivo);
                parser.run();
                
                
                String aux = analizadorLexico.mostrarTs();
                tSimbolPane.setText(aux);
                //mostrar errores sintacticos
                //set_text_output(analizadorSintactico.getErroresSint());           

                //mostrar estructura
                //set_text_output(analizadorSintactico.getEstructuras());             
                
                //set_text_output (analizadorLexico.mostrarTokens());
            }
        });

        err_sint.setText("Errores Sintacticos");
        err_sint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	String aux = "Errores Sintacticos: <br>" + analizadorSintactico.getErroresSint() + "<br>";
            	set_text_output(aux);
            }
        });

        err_lex.setText("Errores Lexicos");
        err_lex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	String aux = "Errores Compilacion: <br>" + analizadorLexico.mostrarErrorComp() + "<br>";
            	set_text_output(aux);
            }
        });
        
        estruct.setText("Estructuras");
        estruct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	String aux = "Estructuras encontradas: <br>" + analizadorSintactico.getEstructuras() + "<br>";
            	set_text_output(aux);
            }
        });

        warn.setText("Warning");
        warn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	String aux = "Errores Warning: <br>" + analizadorLexico.mostrarWarning() + "<br>";
            	set_text_output(aux);
            }
        });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(116, 116, 116)
                                .addComponent(err_sint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(err_lex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(warn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estruct)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tSimbolPane, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_agregar_archivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_compilar)
                                .addGap(28, 28, 28)
                                .addComponent(textFieldTokenActual, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_agregar_archivo)
                    .addComponent(button_compilar)
                    .addComponent(textFieldTokenActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(err_sint)
                            .addComponent(err_lex)
                            .addComponent(warn)
                            .addComponent(estruct))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tSimbolPane)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );


    pack();
	setVisible(true);
	}// </editor-fold>                              
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton err_lex;
    private javax.swing.JButton err_sint;
    private javax.swing.JButton estruct;
    private javax.swing.JButton button_compilar;
    private javax.swing.JButton jButton_agregar_archivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private JTextPane outPut_TextArea;
    private javax.swing.JTextField textFieldTokenActual;
    private javax.swing.JTextPane tSimbolPane;
    private javax.swing.JButton warn;
    // End of variables declaration                 
}
